### PR TITLE
Adding spring-cloud-services-starter-config-client as a dependency

### PR DESCRIPTION
**Pull request by sobychacko**
Resolves https://github.com/spring-cloud-stream-app-starters/app-starters-release/issues/80

### CODE REVIEW

**Comment by trisberg** [comment]
LGTM, built http and jdbc locally and they ran fine. Also tested on k8s without problems.

**Comment by ilayaperumalg** [comment]
Adding any of the `spring-cloud-services` starter as a dependency to the core would bring in `spring-cloud-core` into app's classpath. This could potentially cause some side effect from the Spring Cloud Service connectors especially in CF environment. 

One such example would be, the Spring Cloud Stream Rabbit binder has the conditional [configuration](https://github.com/spring-cloud/spring-cloud-stream-binder-rabbit/blob/master/spring-cloud-stream-binder-rabbit/src/main/java/org/springframework/cloud/stream/binder/rabbit/config/RabbitServiceAutoConfiguration.java#L66) that will be active only if `spring-cloud-core` is in it's classpath.
But adding the `spring-cloud-services-starter-config-client` dependency would bring in following dependencies:

```
\- io.pivotal.spring.cloud:spring-cloud-services-starter-config-client:jar:1.4.1.RELEASE:compile
[INFO] |     +- org.springframework.security.oauth:spring-security-oauth2:jar:2.0.13.RELEASE:runtime
[INFO] |     |  +- commons-codec:commons-codec:jar:1.10:compile
[INFO] |     |  \- org.codehaus.jackson:jackson-mapper-asl:jar:1.9.13:runtime
[INFO] |     |     \- org.codehaus.jackson:jackson-core-asl:jar:1.9.13:runtime
[INFO] |     +- io.pivotal.spring.cloud:spring-cloud-services-cloudfoundry-connector:jar:1.4.1.RELEASE:compile
[INFO] |     |  +- io.pivotal.spring.cloud:spring-cloud-services-connector-core:jar:1.4.1.RELEASE:compile
[INFO] |     |  |  \- org.springframework.cloud:spring-cloud-core:jar:1.2.3.RELEASE:compile
[INFO] |     |  \- org.springframework.cloud:spring-cloud-cloudfoundry-connector:jar:1.2.3.RELEASE:compile
[INFO] |     +- io.pivotal.spring.cloud:spring-cloud-services-spring-connector:jar:1.4.1.RELEASE:compile
[INFO] |     |  +- org.projectlombok:lombok:jar:1.16.14:compile
[INFO] |     |  \- org.springframework.cloud:spring-cloud-spring-service-connector:jar:1.2.3.RELEASE:compile
[INFO] |     \- io.pivotal.spring.cloud:cloudfoundry-certificate-truster:jar:1.0.1.RELEASE:compile
```

which means the `spring-cloud-core` is **always** in the app's classpath.

**Comment by trisberg** [comment]
I found one issue. This is added to the config:

```
"springCloudServicesBootstrap": {
   "spring.application.name": "${vcap.application.name:}"
},
```

This means that in a non-cf environment `spring.application.name` is set to "" as we can see in the config server lookup log message:

```
2017-04-05 09:57:35.312  WARN 77753 --- [           main] c.c.c.ConfigServicePropertySourceLocator : Could not locate PropertySource: I/O error on GET request for "http://localhost:8888//default": Connection refused; nested exception is java.net.ConnectException: Connection refused
```

**Comment by mbogoevici** [comment]
Re: https://github.com/spring-cloud-stream-app-starters/core/pull/18#issuecomment-291797078 , following a brief discussion with @markpollack 

Applications using the Spring Cloud Stream RabbitMQ binder that run in Cloud Foundry are expected to bind to a Rabbit service, and as a result they would normally get `spring-cloud-core` on their classpath anyway - so it is unclear how this would change things from that point of view. 
Under normal use cases the configuration will ensure that the application uses the Rabbit bound service. The current configuration options for the Rabbit binder also allow superseding the Cloud connectors ( `spring.cloud.stream.overrideCloudConnectors`)  and defaulting to Spring Boot properties where the use of a Rabbit service is not desired - one such examples is in the Hystrix Stream client of the SCS tile that uses a completely independent binder.

**Comment by trisberg** [comment]
I think the simplest solution for the `spring.application.name` is to just add a `bootstrap.properties` file to every generated stream app with this content:

```
spring.application.name=${vcap.application.name:log-sink}
```
where `log-sink` is the name of the app we generate this for

**Comment by trisberg** [comment]
LGTM now, merging ...

**Pull request merged**
